### ISSUE TITLE
[UMBRELLA] Move CI/CD out of CircleCI

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#1215]
This is an umbrella issue.

**Motivation**

We decided to move all the CI/CD pipelines out of CircleCI.

**Feature**

This umbrella issue tracks the work needed to migrate pipelines that are currently running in CircleCI.

**Alternatives**

NA

**Additional context**

NA

```[tasklist]
### Tasks
- [ ] https://github.com/falcosecurity/test-infra/issues/1211
- [ ] https://github.com/falcosecurity/test-infra/issues/1153
- [ ] https://github.com/falcosecurity/test-infra/issues/1155
```
