### ISSUE TITLE
Umbrella Issue to Separate Falco build process from internal Sysdig CI system

### ISSUE THREAD

**Issue by markyjackson-taulia** [falcosecurity/test-infra#52]
We need to separate Falco build process from internal Sysdig CI system.

- [] Determine the build system,
- [] Determine what the build process currently looks like
- [] Make new build publicly viewable
- [] Runbook for dealing with fail builds

**Comment by leodido** [comment]
This is completely done by some time now.

/close
