### ISSUE TITLE
Add poiana to cloud native security hub repos

### ISSUE THREAD

**Issue by leodido** [falcosecurity/test-infra#68]
We need to setup Prow workflow for these repositories:

- https://github.com/falcosecurity/cloud-native-security-hub
- https://github.com/falcosecurity/cloud-native-security-hub-frontend
- https://github.com/falcosecurity/cloud-native-security-hub-backend

## Subtasks

- [x] OWNERS (approvals, and reviewers)
- [x] kind labels
- [ ] protect master branches
- [ ] enforce rebase merging strategy
- [ ] release notes (changelog) mechanism from PRs
- [ ] do not merge strategies (WIP, needs rebase, missing release notes, invalid owners)
- [ ] detect missing kind/* labels (issues, PR)
- [ ] plugins

cc @nestorsalceda @bencer
